services:
  rbassoon_spacetime:
    build:
      context: server
    restart: always
#    command: cargo run
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=full
    volumes:
      - ./server/:/app
      - db-data:/stdb
    ports:
      - 6969:80

volumes:
  db-data:
