### GET request with a header
GET http://localhost:6969/task/list
Accept: application/json


### Send POST request with json body
POST http://localhost:6969/task/add
Content-Type: application/json

{
    "task_name": "content"
}
