### GET request with a header
GET http://localhost:8080/task/spacetime
Accept: application/json

### GET request with a header
GET http://localhost:8080/task/spacetime_hello
Accept: application/json

### GET request with a header
GET http://localhost:6868/database/ping
Accept: application/json
