### POST request with a header
POST http://localhost:3000/identity
Accept: application/json

### GET request with a header
GET http://localhost:6969/database/ping
Accept: application/json

### GET request with a header
GET http://localhost:6969/call/repository/hello
Accept: application/json

### GET request with a header
GET http://localhost:3000/database/logs/ae2af243fc1ae661497b7647428c4200
Content-Type: application/json
Authorization: Basic

{
  "num_lines": 1,
  "follow": false
}
